stages:
  - builds

.multilib: &multilib |
  dpkg_architecture=$(which dpkg-architecture 2>/dev/null || true)
  rpm=$(which rpm 2>/dev/null || true)
  if test -x "$dpkg_architecture"; then
    multilib=$(dpkg-architecture -q DEB_TARGET_MULTIARCH);
  elif test -x "$rpm"; then
    multilib=$(rpm --eval '%{_lib}');
  fi

.environment: &environment |
  export VIRT_PREFIX="$HOME/build/libvirt"
  export PATH="$VIRT_PREFIX/bin:$PATH"
  export C_INCLUDE_PATH="$VIRT_PREFIX/include"
  export LD_LIBRARY_PATH="$VIRT_PREFIX/$multilib"
  export PKG_CONFIG_PATH="$VIRT_PREFIX/$multilib/pkgconfig"
  export XDG_DATA_DIRS="$VIRT_PREFIX/share:/usr/share:/usr/local/share"
  export GI_TYPELIB_PATH="$VIRT_PREFIX/$multilib/girepository-1.0"
  export OSINFO_SYSTEM_DIR="$VIRT_PREFIX/share/osinfo"
  export CCACHE_BASEDIR="$(pwd)"
  export CCACHE_DIR="$CCACHE_BASEDIR/ccache"
  export CCACHE_MAXSIZE="50M"
  export PATH="$CCACHE_WRAPPERSDIR:$PATH"

.mingw-environment: &mingw-environment |
  export VIRT_PREFIX="$VIRT_PREFIX/$ABI/sys-root/mingw"
  export PKG_CONFIG_PATH="$VIRT_PREFIX/lib/pkgconfig"

.dco: &dco |
  pushd .
  ./scripts/require-dco.sh
  popd

.osinfo-db-tools-build: &osinfo-db-tools-build |
  pushd .
  mkdir build
  cd build
  meson .. . --prefix=$VIRT_PREFIX --werror
  $NINJA install
  popd

.osinfo-db-tools-check: &osinfo-db-tools-check |
  pushd .
  cd build
  $NINJA test
  popd

.osinfo-db-tools-rpm: &osinfo-db-tools-rpm |
  if test "$RPM" = "skip"; then
    exit 0
  fi
  pushd .
  cd build
  $NINJA dist
  rpmbuild --clean --define "_topdir `pwd`/rpmbuild" -ta meson-dist/*.tar.xz
  popd

.osinfo-db-tools-mingw-build: &osinfo-db-tools-mingw-build |
  pushd .
  mkdir build
  cd build
  meson .. . --cross-file=/usr/share/mingw/toolchain-$CROSS.meson --prefix=$VIRT_PREFIX --werror
  $NINJA
  $NINJA install
  popd

.x86_64-build-job-deb: &x86_64-build-job-deb
  stage: builds
  image: quay.io/libvirt/buildenv-libosinfo-$NAME:latest
  cache:
    paths:
      - ccache
    key: "$CI_JOB_NAME"
  script:
    - *multilib
    - *environment
    - *dco
    - *osinfo-db-tools-build
    - *osinfo-db-tools-check

.x86_64-build-job-rpm: &x86_64-build-job-rpm
  stage: builds
  image: quay.io/libvirt/buildenv-libosinfo-$NAME:latest
  cache:
    paths:
      - ccache
    key: "$CI_JOB_NAME"
  script:
    - *multilib
    - *environment
    - *dco
    - *osinfo-db-tools-build
    - *osinfo-db-tools-check
    - *osinfo-db-tools-rpm

.mingw-build-job: &mingw-build-job
  stage: builds
  image: quay.io/libvirt/buildenv-libosinfo-$NAME-cross-$CROSS:latest
  cache:
    paths:
      - ccache
    key: "$CI_JOB_NAME"
  script:
    - *multilib
    - *environment
    - *dco
    - *mingw-environment
    - *osinfo-db-tools-mingw-build

centos-7:
  <<: *x86_64-build-job-rpm
  variables:
    NAME: centos-7
    RPM: skip

centos-8:
  script:
  <<: *x86_64-build-job-rpm
  variables:
    NAME: centos-8

debian-9:
  <<: *x86_64-build-job-deb
  variables:
    NAME: debian-9

debian-10:
  <<: *x86_64-build-job-deb
  variables:
    NAME: debian-10

debian-sid:
  <<: *x86_64-build-job-deb
  variables:
    NAME: debian-sid

fedora-31:
  <<: *x86_64-build-job-rpm
  variables:
    NAME: fedora-31

fedora-32:
  <<: *x86_64-build-job-rpm
  variables:
    NAME: fedora-32

fedora-rawhide:
  <<: *x86_64-build-job-rpm
  variables:
    NAME: fedora-rawhide

fedora-rawhide-cross-mingw32:
  <<: *mingw-build-job
  variables:
    NAME: fedora-rawhide
    CROSS: mingw32

fedora-rawhide-cross-mingw64:
  <<: *mingw-build-job
  variables:
    NAME: fedora-rawhide
    CROSS: mingw64

opensuse-151:
  <<: *x86_64-build-job-rpm
  variables:
    NAME: opensuse-151
    RPM: skip

ubuntu-1804:
  <<: *x86_64-build-job-deb
  variables:
    NAME: ubuntu-1804

ubuntu-2004:
  <<: *x86_64-build-job-deb
  variables:
    NAME: ubuntu-2004
